server:
  port: 8080

spring:
  application:
    name: customer
  datasource:
    username: 'abdaziz'
    url: jdbc:postgresql://localhost:5432/customer
    password: 'P@ssw0rd'
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: 'true'
      hibernate:
        ddl-auto: update
      show-sql: 'true'
