services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: abdaziz
      POSTGRES_PASSWORD: P@ssw0rd
      PGDATA: /data/postgres
    volumes:
      - postgres_data:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: dev.abdaziz@outlook.com
      PGADMIN_DEFAULT_PASSWORD: P@ssw0rd
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:
